platform :ios, '17.0'
install! 'cocoapods', :disable_input_output_paths => true

project 'RaverMVP.xcodeproj'

use_frameworks! :linkage => :static
use_modular_headers!

target 'RaverMVP' do
  pod 'TXIMSDK_Plus_iOS_XCFramework', '8.9.7511'
  pod 'SDWebImageSwiftUI', '3.1.4'
  pod 'SnapKit', :path => '../../../thirdparty/SnapKit-5.7.1'
  pod 'TUICore', :path => '../../../thirdparty/Chat_UIKit-main/Swift/TUIKit/TUICore'
  pod 'TIMCommon_Swift', :path => '../../../thirdparty/Chat_UIKit-main/Swift/TUIKit/TIMCommon'
  pod 'TUIChat_Swift', :path => '../../../thirdparty/Chat_UIKit-main/Swift/TUIKit/TUIChat'
  pod 'TUIConversation_Swift', :path => '../../../thirdparty/Chat_UIKit-main/Swift/TUIKit/TUIConversation'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['STRIP_SWIFT_SYMBOLS'] = 'NO'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
