import 'package:flutter_test/flutter_test.dart';
import 'package:ravehub/router/deep_link_handler.dart';

void main() {
  group('DeepLinkHandler', () {
    test('maps iOS canonical custom-scheme aliases', () {
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('raver://community/post/post-1')),
        '/circle/post/post-1',
      );
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('raver://profile/user-1')),
        '/users/user-1',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('raver://circle/rating-event/rating-1'),
        ),
        '/circle/ratings/rating-1',
      );
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('raver://profile/checkins')),
        '/profile/checkins',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('raver://circle/ratings/rating-1/units/unit-1'),
        ),
        '/circle/ratings/rating-1/units/unit-1',
      );
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('raver://profile/contributions')),
        '/profile/contributions',
      );
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('raver://profile/quiz')),
        '/profile/quiz',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('raver://profile/settings/account-security'),
        ),
        '/profile/settings/account-security',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('raver://messages/followed-events'),
        ),
        '/inbox/followed-events',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('raver://messages/content-reviews'),
        ),
        '/inbox/content-reviews',
      );
    });

    test('maps iOS canonical universal-link aliases', () {
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://ravehub.top/p/post-1?shareCode=abc'),
        ),
        '/circle/post/post-1?shareCode=abc',
      );
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('https://ravehub.top/e/event-1')),
        '/events/event-1',
      );
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('https://ravehub.top/u/user-1')),
        '/users/user-1',
      );
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('https://ravehub.top/g/squad-1')),
        '/circle/squads/squad-1',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://ravehub.top/profile/checkins'),
        ),
        '/profile/checkins',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse(
            'https://ravehub.top/circle/ratings/rating-1/units/unit-1',
          ),
        ),
        '/circle/ratings/rating-1/units/unit-1',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://ravehub.top/profile/contributions'),
        ),
        '/profile/contributions',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://ravehub.top/profile/personality'),
        ),
        '/profile/personality',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://ravehub.top/profile/tools/route'),
        ),
        '/profile/tools/route',
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://ravehub.top/messages/followed-djs'),
        ),
        '/inbox/followed-djs',
      );
    });

    test('leaves short links for the async live resolver', () {
      expect(
        DeepLinkHandler.toAppPath(Uri.parse('https://ravehub.top/s/abc123')),
        isNull,
      );
    });

    test('rejects lookalike universal-link hosts', () {
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://evil-ravehub.top/events/event-1'),
        ),
        isNull,
      );
      expect(
        DeepLinkHandler.toAppPath(
          Uri.parse('https://ravehub.top.evil.test/events/event-1'),
        ),
        isNull,
      );
    });
  });
}
