-- AlterTable
ALTER TABLE "djs" ADD COLUMN     "avatar_source_url" TEXT,
ADD COLUMN     "source_added_at" TIMESTAMP(3),
ADD COLUMN     "source_artist_type" TEXT,
ADD COLUMN     "source_birth_date" TEXT,
ADD COLUMN     "source_booking_agency" TEXT,
ADD COLUMN     "source_booking_agent" TEXT,
ADD COLUMN     "source_booking_url" TEXT,
ADD COLUMN     "source_data_source" TEXT,
ADD COLUMN     "source_discography_count" INTEGER,
ADD COLUMN     "source_genres" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "source_id" TEXT,
ADD COLUMN     "source_labels" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "source_last_enriched_at" TIMESTAMP(3),
ADD COLUMN     "source_last_image_attempt_at" TIMESTAMP(3),
ADD COLUMN     "source_lineup_city_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "source_lineup_event_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "source_nationality" TEXT,
ADD COLUMN     "source_next_image_attempt_at" TIMESTAMP(3),
ADD COLUMN     "source_promotion_score" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "source_real_name" TEXT,
ADD COLUMN     "source_same_as" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "source_setlistfm_fetched_at" TIMESTAMP(3),
ADD COLUMN     "source_setlistfm_mbid" TEXT,
ADD COLUMN     "source_setlistfm_url" TEXT,
ADD COLUMN     "source_tiktok" TEXT,
ADD COLUMN     "source_total_votes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "source_trending_score" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "source_upcoming_shows" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "source_updated_at" TIMESTAMP(3),
ADD COLUMN     "source_verification_score" INTEGER,
ADD COLUMN     "source_website" TEXT,
ADD COLUMN     "source_wikipedia" TEXT,
ADD COLUMN     "source_years_active" TEXT;
