ALTER TABLE "genres"
  ADD COLUMN IF NOT EXISTS "name_i18n" JSONB,
  ADD COLUMN IF NOT EXISTS "sound_cue_tracks" JSONB,
  ADD COLUMN IF NOT EXISTS "origin" TEXT,
  ADD COLUMN IF NOT EXISTS "era" TEXT,
  ADD COLUMN IF NOT EXISTS "bpm" TEXT,
  ADD COLUMN IF NOT EXISTS "background_image_url" TEXT;
